export const ARCHIVE_COPY = {
  en: {
    archiveQuestion: "Question",
    archiveSource: "Source",
    archiveBestAnswer: "Best answer",
    noAnswer: "No answer",
    collectAnswers: "Collect and copy selected answers",
    openArchive: "Open result library",
    archiveTitle: "Result library",
    closeArchive: "Close result library",
    archiveSearch: "Search questions and answers…",
    favoriteArchives: "Favorites",
    favoriteArchive: "Add to favorites",
    unfavoriteArchive: "Remove from favorites",
    allArchiveTags: "All tags",
    captureArchive: "Capture current answers",
    copyArchive: "Copy Markdown",
    exportArchive: "Export Markdown",
    deleteArchive: "Delete result",
    confirmDeleteArchive: "Delete this result?",
    archiveTags: "Tags",
    archiveNote: "Note",
    markBest: "Mark best",
    unmarkBest: "Unmark best",
    archiveLoading: "Loading results…",
    archiveEmpty: "No saved results yet",
    archiveNoMatches: "No matching results",
    archiveLoadFailed: "Could not load the result library",
    archiveSaveFailed: "Could not save changes",
    archiveCollectFailed: "Could not collect current answers",
    archiveCollected: "Answers saved and Markdown copied",
    archiveSaved: "Current answers saved",
    archiveCopied: "Markdown copied",
    archiveExported: "Markdown exported",
    archiveCapturedAt: "Captured {time}"
  },
  zhCN: {
    archiveQuestion: "问题",
    archiveSource: "来源",
    archiveBestAnswer: "最佳回答",
    noAnswer: "暂无回答",
    collectAnswers: "汇总复制已选回答",
    openArchive: "打开结果库",
    archiveTitle: "结果库",
    closeArchive: "关闭结果库",
    archiveSearch: "搜索问题与回答…",
    favoriteArchives: "仅看收藏",
    favoriteArchive: "添加收藏",
    unfavoriteArchive: "取消收藏",
    allArchiveTags: "全部标签",
    captureArchive: "采集当前回答",
    copyArchive: "复制 Markdown",
    exportArchive: "导出 Markdown",
    deleteArchive: "删除结果",
    confirmDeleteArchive: "确认删除这条结果？",
    archiveTags: "标签",
    archiveNote: "备注",
    markBest: "标为最佳",
    unmarkBest: "取消最佳",
    archiveLoading: "正在加载结果…",
    archiveEmpty: "暂无已保存结果",
    archiveNoMatches: "没有匹配结果",
    archiveLoadFailed: "结果库加载失败",
    archiveSaveFailed: "修改保存失败",
    archiveCollectFailed: "当前回答采集失败",
    archiveCollected: "回答已保存并复制 Markdown",
    archiveSaved: "当前回答已保存",
    archiveCopied: "已复制 Markdown",
    archiveExported: "已导出 Markdown",
    archiveCapturedAt: "采集于 {time}"
  },
  zhTW: {
    archiveQuestion: "問題",
    archiveSource: "來源",
    archiveBestAnswer: "最佳回答",
    noAnswer: "暫無回答",
    collectAnswers: "彙整複製已選回答",
    openArchive: "開啟結果庫",
    archiveTitle: "結果庫",
    closeArchive: "關閉結果庫",
    archiveSearch: "搜尋問題與回答…",
    favoriteArchives: "僅看收藏",
    favoriteArchive: "加入收藏",
    unfavoriteArchive: "取消收藏",
    allArchiveTags: "全部標籤",
    captureArchive: "擷取目前回答",
    copyArchive: "複製 Markdown",
    exportArchive: "匯出 Markdown",
    deleteArchive: "刪除結果",
    confirmDeleteArchive: "確認刪除這筆結果？",
    archiveTags: "標籤",
    archiveNote: "備註",
    markBest: "標為最佳",
    unmarkBest: "取消最佳",
    archiveLoading: "正在載入結果…",
    archiveEmpty: "尚無已儲存結果",
    archiveNoMatches: "沒有符合的結果",
    archiveLoadFailed: "結果庫載入失敗",
    archiveSaveFailed: "變更儲存失敗",
    archiveCollectFailed: "目前回答擷取失敗",
    archiveCollected: "回答已儲存並複製 Markdown",
    archiveSaved: "目前回答已儲存",
    archiveCopied: "已複製 Markdown",
    archiveExported: "已匯出 Markdown",
    archiveCapturedAt: "擷取於 {time}"
  }
} as const;
