import { ARCHIVE_COPY } from "./archive-copy";
import { SYNC_COPY } from "./sync-copy";
import { SYNTHESIS_COPY } from "./synthesis-copy";

export const COPY = {
  en: {
    ...ARCHIVE_COPY.en,
    ...SYNC_COPY.en,
    ...SYNTHESIS_COPY.en,
    appTitle: "PolyAsk · AI Answers",
    overview: "Grid",
    focus: "Focus",
    layoutLabel: "View layout",
    selectedSummary: "{selected} / {total} selected",
    sendingSummary: "Sending to {count} sites",
    scope: "Site scope",
    closeScope: "Close site scope",
    newSessionSelected: "New session for selected sites",
    allSites: "All",
    clearSites: "Clear",
    imageSites: "Images",
    intlSites: "International",
    domesticSites: "Domestic",
    selectedSites: "Selected sites",
    savedGroups: "Saved groups",
    noSavedGroups: "No saved groups",
    groupNamePlaceholder: "Group name",
    saveGroup: "Save current selection",
    deleteGroup: "Delete {group}",
    confirmDeleteGroup: "Delete {group}?",
    confirmDelete: "Delete",
    cancelDelete: "Keep",
    workspaceActionFailed: "Workspace action failed",
    addImages: "Add images",
    manageImages: "Manage {count} images",
    closeImages: "Close image list",
    replaceImages: "Replace images",
    removeImage: "Remove {name}",
    imagesReady: "{count} images selected",
    imageCountError: "Choose 1 to 4 images",
    imageTypeError: "Only PNG and JPEG images are supported",
    imageSizeError: "Images must total 10 MiB or less",
    imageInvalid: "An image could not be read safely",
    imageUnsupported: "{sites} do not support image broadcasts; adjust site scope",
    adjustImageScope: "Adjust site scope: {count} unsupported",
    imagePayloadInvalid: "Image payload is invalid",
    attachmentUnsupported: "This site does not support image broadcasts",
    attachmentFailed: "Could not attach images",
    attachmentTimedOut: "Timed out waiting for image attachments",
    attachmentActionRequired: "Finish the image attachment action on this site",
    broadcastLabel: "Broadcast prompt",
    promptPlaceholder: "Ask one question across the selected AI sites…",
    promptLabel: "Prompt",
    tierLabel: "Response mode",
    followSite: "Use site setting",
    fast: "Fast",
    think: "Deep thinking",
    cancel: "Cancel",
    cancelling: "Cancelling…",
    send: "Send",
    siteViews: "AI site views",
    selectSite: "Send to {site}",
    focusSite: "Focus {site}",
    reloadSite: "Reload {site}",
    loading: "Loading",
    ready: "Ready",
    sending: "Sending",
    submitted: "Sent",
    submittedWithWarning: "Sent with warning",
    tierUnconfirmed: "Sent; response mode not confirmed",
    composerNotFound: "Prompt box not found",
    siteNotReady: "Site not ready",
    submitUnconfirmed: "Whether it was sent is unconfirmed",
    timedOut: "Timed out",
    cancelledStatus: "Cancelled",
    injectFailed: "Could not fill prompt",
    siteUnavailable: "Site view unavailable",
    loadFailed: "Page failed to load",
    failed: "Failed",
    crashed: "Stopped",
    fileMenu: "File",
    editMenu: "Edit",
    viewMenu: "View",
    windowMenu: "Window",
    focusPromptMenu: "Focus prompt input",
    nextSiteMenu: "Focus next site",
    previousSiteMenu: "Focus previous site",
    densityMenu: "Interface density",
    compactDensity: "Compact",
    comfortableDensity: "Comfortable",
    siteScaleMenu: "Site scale",
    fitSiteScale: "Fit (90%)",
    actualSiteScale: "Actual size (100%)"
  },
  zhCN: {
    ...ARCHIVE_COPY.zhCN,
    ...SYNC_COPY.zhCN,
    ...SYNTHESIS_COPY.zhCN,
    appTitle: "PolyAsk · AI 众答",
    overview: "九宫格",
    focus: "聚焦",
    layoutLabel: "视图布局",
    selectedSummary: "已选择 {selected} / {total}",
    sendingSummary: "正在向 {count} 个站点发送",
    scope: "站点范围",
    closeScope: "关闭站点范围",
    newSessionSelected: "为已选站点新建会话",
    allSites: "全部",
    clearSites: "清空",
    imageSites: "支持图片",
    intlSites: "国外",
    domesticSites: "国内",
    selectedSites: "已选站点",
    savedGroups: "已存分组",
    noSavedGroups: "暂无分组",
    groupNamePlaceholder: "分组名称",
    saveGroup: "保存当前选择",
    deleteGroup: "删除{group}",
    confirmDeleteGroup: "删除{group}？",
    confirmDelete: "删除",
    cancelDelete: "保留",
    workspaceActionFailed: "工作区操作失败",
    addImages: "添加图片",
    manageImages: "管理 {count} 张图片",
    closeImages: "关闭图片列表",
    replaceImages: "更换图片",
    removeImage: "移除{name}",
    imagesReady: "已选择 {count} 张图片",
    imageCountError: "请选择 1 至 4 张图片",
    imageTypeError: "仅支持 PNG 和 JPEG 图片",
    imageSizeError: "图片总大小不能超过 10 MiB",
    imageInvalid: "有图片无法安全读取",
    imageUnsupported: "{sites} 不支持图片群发，请调整站点范围",
    adjustImageScope: "调整站点范围：{count} 个不支持",
    imagePayloadInvalid: "图片载荷无效",
    attachmentUnsupported: "该站点不支持图片群发",
    attachmentFailed: "图片附件添加失败",
    attachmentTimedOut: "等待图片附件超时",
    attachmentActionRequired: "请在该站点完成图片附件操作",
    broadcastLabel: "群发提问",
    promptPlaceholder: "输入一个问题，同时发送到选中的 AI…",
    promptLabel: "提问内容",
    tierLabel: "回答档位",
    followSite: "跟随站点",
    fast: "快速",
    think: "深度思考",
    cancel: "取消",
    cancelling: "正在取消…",
    send: "发送",
    siteViews: "AI 站点视图",
    selectSite: "群发到 {site}",
    focusSite: "聚焦 {site}",
    reloadSite: "重新加载 {site}",
    loading: "加载中",
    ready: "就绪",
    sending: "发送中",
    submitted: "已发送",
    submittedWithWarning: "已发送（有警示）",
    tierUnconfirmed: "已发送，回答档位未确认",
    composerNotFound: "未找到输入框",
    siteNotReady: "站点尚未就绪",
    submitUnconfirmed: "是否发送成功尚未确认",
    timedOut: "发送超时",
    cancelledStatus: "已取消",
    injectFailed: "未能填写提问",
    siteUnavailable: "站点视图不可用",
    loadFailed: "页面加载失败",
    failed: "失败",
    crashed: "已停止",
    fileMenu: "文件",
    editMenu: "编辑",
    viewMenu: "视图",
    windowMenu: "窗口",
    focusPromptMenu: "聚焦提问框",
    nextSiteMenu: "聚焦下一个站点",
    previousSiteMenu: "聚焦上一个站点",
    densityMenu: "界面密度",
    compactDensity: "紧凑",
    comfortableDensity: "舒适",
    siteScaleMenu: "站点缩放",
    fitSiteScale: "适应（90%）",
    actualSiteScale: "原始大小（100%）"
  },
  zhTW: {
    ...ARCHIVE_COPY.zhTW,
    ...SYNC_COPY.zhTW,
    ...SYNTHESIS_COPY.zhTW,
    appTitle: "PolyAsk · AI 眾答",
    overview: "九宮格",
    focus: "聚焦",
    layoutLabel: "檢視版面",
    selectedSummary: "已選取 {selected} / {total}",
    sendingSummary: "正在傳送到 {count} 個網站",
    scope: "網站範圍",
    closeScope: "關閉網站範圍",
    newSessionSelected: "為已選網站新增對話",
    allSites: "全部",
    clearSites: "清除",
    imageSites: "支援圖片",
    intlSites: "國外",
    domesticSites: "國內",
    selectedSites: "已選網站",
    savedGroups: "已儲存群組",
    noSavedGroups: "尚無群組",
    groupNamePlaceholder: "群組名稱",
    saveGroup: "儲存目前選取",
    deleteGroup: "刪除{group}",
    confirmDeleteGroup: "刪除{group}？",
    confirmDelete: "刪除",
    cancelDelete: "保留",
    workspaceActionFailed: "工作區操作失敗",
    addImages: "加入圖片",
    manageImages: "管理 {count} 張圖片",
    closeImages: "關閉圖片清單",
    replaceImages: "更換圖片",
    removeImage: "移除{name}",
    imagesReady: "已選取 {count} 張圖片",
    imageCountError: "請選取 1 至 4 張圖片",
    imageTypeError: "僅支援 PNG 和 JPEG 圖片",
    imageSizeError: "圖片總大小不能超過 10 MiB",
    imageInvalid: "有圖片無法安全讀取",
    imageUnsupported: "{sites} 不支援圖片群發，請調整網站範圍",
    adjustImageScope: "調整網站範圍：{count} 個不支援",
    imagePayloadInvalid: "圖片載荷無效",
    attachmentUnsupported: "該網站不支援圖片群發",
    attachmentFailed: "圖片附件加入失敗",
    attachmentTimedOut: "等待圖片附件逾時",
    attachmentActionRequired: "請在該網站完成圖片附件操作",
    broadcastLabel: "群發提問",
    promptPlaceholder: "輸入一個問題，同時傳送到選取的 AI…",
    promptLabel: "提問內容",
    tierLabel: "回答模式",
    followSite: "依網站設定",
    fast: "快速",
    think: "深度思考",
    cancel: "取消",
    cancelling: "正在取消…",
    send: "傳送",
    siteViews: "AI 網站檢視",
    selectSite: "傳送到 {site}",
    focusSite: "聚焦 {site}",
    reloadSite: "重新載入 {site}",
    loading: "載入中",
    ready: "就緒",
    sending: "傳送中",
    submitted: "已傳送",
    submittedWithWarning: "已傳送（有警示）",
    tierUnconfirmed: "已傳送，回答模式未確認",
    composerNotFound: "找不到輸入框",
    siteNotReady: "網站尚未就緒",
    submitUnconfirmed: "是否送出尚未確認",
    timedOut: "傳送逾時",
    cancelledStatus: "已取消",
    injectFailed: "無法填入提問",
    siteUnavailable: "網站檢視無法使用",
    loadFailed: "頁面載入失敗",
    failed: "失敗",
    crashed: "已停止",
    fileMenu: "檔案",
    editMenu: "編輯",
    viewMenu: "檢視",
    windowMenu: "視窗",
    focusPromptMenu: "聚焦提問框",
    nextSiteMenu: "聚焦下一個網站",
    previousSiteMenu: "聚焦上一個網站",
    densityMenu: "介面密度",
    compactDensity: "緊湊",
    comfortableDensity: "舒適",
    siteScaleMenu: "網站縮放",
    fitSiteScale: "適應（90%）",
    actualSiteScale: "原始大小（100%）"
  }
} as const;

export type DesktopCopy = { readonly [Key in keyof typeof COPY.en]: string };
export type DesktopLocale = keyof typeof COPY;

export function resolveLocale(rawLocale: string): DesktopLocale {
  const locale = rawLocale.toLowerCase();
  if (locale === "zh" || locale.startsWith("zh-cn") || locale.startsWith("zh-hans")) return "zhCN";
  if (
    locale.startsWith("zh-tw") ||
    locale.startsWith("zh-hk") ||
    locale.startsWith("zh-mo") ||
    locale.startsWith("zh-hant")
  ) return "zhTW";
  return "en";
}

export function getCopy(rawLocale: string): DesktopCopy {
  return COPY[resolveLocale(rawLocale)];
}

export function formatCopy(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{([a-z]+)\}/g, (token, key: string) =>
    Object.prototype.hasOwnProperty.call(values, key) ? String(values[key]) : token
  );
}
