export const PROMPT_LIBRARY_COPY = {
  en: {
    promptLibrary: "Prompt library",
    showPromptLibrary: "Prompt library",
    promptLibrarySearch: "Search templates and recent prompts",
    promptTemplates: "Templates",
    recentQuestions: "Recent prompts",
    promptTemplateName: "Template name",
    saveCurrentPrompt: "Save current prompt",
    deleteTemplate: "Delete template",
    promptLibraryEmpty: "No matching templates or recent prompts",
    promptLibrarySaveFailed: "Could not save the prompt template",
    promptLibraryDeleteFailed: "Could not delete the prompt template",
  },
  zhCN: {
    promptLibrary: "提问库",
    showPromptLibrary: "提问库",
    promptLibrarySearch: "搜索模板和最近提问",
    promptTemplates: "提问模板",
    recentQuestions: "最近提问",
    promptTemplateName: "模板名称",
    saveCurrentPrompt: "保存当前提问",
    deleteTemplate: "删除模板",
    promptLibraryEmpty: "没有匹配的模板或最近提问",
    promptLibrarySaveFailed: "无法保存提问模板",
    promptLibraryDeleteFailed: "无法删除提问模板",
  },
  zhTW: {
    promptLibrary: "提問庫",
    showPromptLibrary: "提問庫",
    promptLibrarySearch: "搜尋範本和最近提問",
    promptTemplates: "提問範本",
    recentQuestions: "最近提問",
    promptTemplateName: "範本名稱",
    saveCurrentPrompt: "儲存目前提問",
    deleteTemplate: "刪除範本",
    promptLibraryEmpty: "找不到相符的範本或最近提問",
    promptLibrarySaveFailed: "無法儲存提問範本",
    promptLibraryDeleteFailed: "無法刪除提問範本",
  }
} as const;
