export const SYNC_COPY = {
  en: {
    settings: "Settings",
    syncTitle: "Google Drive sync",
    syncDescription: "Sync site scope, groups, prompt history and saved results through PolyAsk's private Drive app folder.",
    syncConnected: "Connected",
    syncDisconnected: "Not connected",
    syncPending: "{count} pending",
    syncLastSuccess: "Last synced {time}",
    syncNever: "Not synced yet",
    syncConnect: "Connect Google Drive",
    syncNow: "Sync now",
    syncDisconnect: "Disconnect",
    syncClearTitle: "Delete cloud data",
    syncClearDescription: "Permanently delete only PolyAsk files from the private Drive app folder. Local data stays on this device.",
    syncClearInstruction: "Type DELETE to enable",
    syncClear: "Delete cloud data",
    syncOauthMissing: "This build has no Google desktop OAuth client ID. Add resources/oauth.json or set POLYASK_GOOGLE_DESKTOP_CLIENT_ID before packaging.",
    syncStorageWarning: "Your Linux keyring is unavailable. The refresh token will remain in memory for this session and will not be written to disk.",
    syncReadOnly: "A newer device wrote an unsupported sync format. Downloads remain available; uploads are paused to protect cloud data.",
    syncStateIdle: "Up to date",
    syncStateLocalOnly: "Local only",
    syncStateSyncing: "Syncing…",
    syncStateOffline: "Offline; local changes are queued",
    syncStateAuth: "Sign in again to continue",
    syncStateBlocked: "Google Drive access is blocked",
    syncStateWaiting: "Google is busy; retry scheduled",
    syncStateSchema: "Read-only compatibility mode",
    syncStateError: "Sync failed",
    syncReasonDriveDisabled: "Enable Google Drive API for this OAuth project",
    syncReasonQuota: "Google Drive quota or rate limit reached",
    syncReasonPolicy: "Google policy denied Drive access",
    syncReasonOauthMissing: "OAuth is not configured",
    syncPrivacy: "Cloud records are plain JSON and are not end-to-end encrypted. PolyAsk requests only drive.appdata access.",
    syncActionFailed: "Sync action failed"
  },
  zhCN: {
    settings: "设置",
    syncTitle: "Google Drive 同步",
    syncDescription: "通过 PolyAsk 的 Drive 应用专属目录同步站点范围、分组、提问历史和结果库。",
    syncConnected: "已连接",
    syncDisconnected: "未连接",
    syncPending: "{count} 项待同步",
    syncLastSuccess: "上次同步 {time}",
    syncNever: "尚未同步",
    syncConnect: "连接 Google Drive",
    syncNow: "立即同步",
    syncDisconnect: "断开连接",
    syncClearTitle: "删除云端数据",
    syncClearDescription: "永久删除 Drive 应用专属目录内的 PolyAsk 文件；本机数据会保留。",
    syncClearInstruction: "输入 DELETE 后启用",
    syncClear: "删除云端数据",
    syncOauthMissing: "当前构建未配置 Google 桌面 OAuth 客户端 ID。打包前请添加 resources/oauth.json 或设置 POLYASK_GOOGLE_DESKTOP_CLIENT_ID。",
    syncStorageWarning: "Linux 密钥环不可用。刷新令牌仅在本次会话保留于内存，不会写入磁盘。",
    syncReadOnly: "其他设备写入了当前版本不支持的同步格式。仍可下载，已暂停上传以保护云端数据。",
    syncStateIdle: "已是最新",
    syncStateLocalOnly: "仅保存在本机",
    syncStateSyncing: "正在同步…",
    syncStateOffline: "当前离线，本机变更已排队",
    syncStateAuth: "请重新登录后继续",
    syncStateBlocked: "Google Drive 访问受阻",
    syncStateWaiting: "Google 服务繁忙，已安排重试",
    syncStateSchema: "只读兼容模式",
    syncStateError: "同步失败",
    syncReasonDriveDisabled: "请为此 OAuth 项目启用 Google Drive API",
    syncReasonQuota: "已达到 Google Drive 配额或请求限制",
    syncReasonPolicy: "Google 策略拒绝了 Drive 访问",
    syncReasonOauthMissing: "尚未配置 OAuth",
    syncPrivacy: "云端记录为明文 JSON，不提供端到端加密；PolyAsk 仅申请 drive.appdata 权限。",
    syncActionFailed: "同步操作失败"
  },
  zhTW: {
    settings: "設定",
    syncTitle: "Google Drive 同步",
    syncDescription: "透過 PolyAsk 的 Drive 應用程式專屬資料夾同步網站範圍、群組、提問記錄與結果庫。",
    syncConnected: "已連線",
    syncDisconnected: "未連線",
    syncPending: "{count} 項待同步",
    syncLastSuccess: "上次同步 {time}",
    syncNever: "尚未同步",
    syncConnect: "連線 Google Drive",
    syncNow: "立即同步",
    syncDisconnect: "中斷連線",
    syncClearTitle: "刪除雲端資料",
    syncClearDescription: "永久刪除 Drive 應用程式專屬資料夾內的 PolyAsk 檔案；本機資料會保留。",
    syncClearInstruction: "輸入 DELETE 後啟用",
    syncClear: "刪除雲端資料",
    syncOauthMissing: "目前組建未設定 Google 桌面 OAuth 用戶端 ID。封裝前請加入 resources/oauth.json 或設定 POLYASK_GOOGLE_DESKTOP_CLIENT_ID。",
    syncStorageWarning: "Linux 金鑰圈無法使用。重新整理權杖僅在本次工作階段保留於記憶體，不會寫入磁碟。",
    syncReadOnly: "其他裝置寫入了目前版本不支援的同步格式。仍可下載，已暫停上傳以保護雲端資料。",
    syncStateIdle: "已是最新",
    syncStateLocalOnly: "僅儲存在本機",
    syncStateSyncing: "正在同步…",
    syncStateOffline: "目前離線，本機變更已排入佇列",
    syncStateAuth: "請重新登入後繼續",
    syncStateBlocked: "Google Drive 存取受阻",
    syncStateWaiting: "Google 服務忙碌，已安排重試",
    syncStateSchema: "唯讀相容模式",
    syncStateError: "同步失敗",
    syncReasonDriveDisabled: "請為此 OAuth 專案啟用 Google Drive API",
    syncReasonQuota: "已達 Google Drive 配額或要求限制",
    syncReasonPolicy: "Google 政策拒絕了 Drive 存取",
    syncReasonOauthMissing: "尚未設定 OAuth",
    syncPrivacy: "雲端記錄為純文字 JSON，不提供端對端加密；PolyAsk 僅要求 drive.appdata 權限。",
    syncActionFailed: "同步操作失敗"
  }
} as const;
