export const SYNTHESIS_COPY = {
  en: {
    synthesisAction: "Synthesize selected answers",
    synthesisTitle: "Assisted synthesis",
    synthesisAnswers: "Candidate answers",
    synthesisCount: "{count} answers selected",
    synthesisTarget: "Target AI",
    synthesisTargetMissing: "Choose a target AI",
    synthesisTargetNotSelected: "Choose a target AI from the current site scope",
    synthesisTier: "Model tier",
    synthesisInstruction: "Synthesis instructions",
    synthesisDefaultInstruction: "Compare these answers. Summarize consensus and disagreements, identify points that need verification, and give a combined conclusion. Do not treat agreement by a majority as proof.",
    synthesisPreview: "Payload preview",
    synthesisTooLong: "The payload is over 60,000 characters and will not be shortened",
    synthesisNotEnough: "Choose at least two answers",
    synthesisUnknownTier: "Tier unknown",
    synthesisSend: "Send for synthesis",
    synthesisSending: "Opening a new target-site session…",
    synthesisSendFailed: "Could not send the synthesis request",
    synthesisSent: "Synthesis request sent; watch the target site, then collect the result",
    synthesisCollect: "Collect synthesis result",
    synthesisCollecting: "Collecting the target site's current answer…",
    synthesisCollectFailed: "Could not collect a synthesis result; keep the target conversation open and try again",
    synthesisSave: "Save to this result",
    synthesisReplace: "Replace synthesis",
    synthesisReplaceConfirm: "Replace the saved synthesis?",
    synthesisSaved: "Synthesis",
    synthesisSavedDone: "Synthesis saved",
    synthesisCancel: "Back to result"
  },
  zhCN: {
    synthesisAction: "综合所选回答",
    synthesisTitle: "辅助综合",
    synthesisAnswers: "候选回答",
    synthesisCount: "已选 {count} 条回答",
    synthesisTarget: "目标 AI",
    synthesisTargetMissing: "请选择目标 AI",
    synthesisTargetNotSelected: "请从当前已选站点中选择目标 AI",
    synthesisTier: "模型档位",
    synthesisInstruction: "综合要求",
    synthesisDefaultInstruction: "比较这些回答，归纳共识与分歧，指出需要核实的内容，并给出综合结论。不要把多数回答一致视为事实依据。",
    synthesisPreview: "载荷预览",
    synthesisTooLong: "载荷超过 60,000 个字符，不会自动裁剪",
    synthesisNotEnough: "请至少选择两条回答",
    synthesisUnknownTier: "档位未知",
    synthesisSend: "发送以综合",
    synthesisSending: "正在打开目标站点的新会话…",
    synthesisSendFailed: "综合请求发送失败",
    synthesisSent: "综合请求已发送；请观察目标站点，完成后采集结果",
    synthesisCollect: "采集综合结果",
    synthesisCollecting: "正在采集目标站点的当前回答…",
    synthesisCollectFailed: "综合结果采集失败，请保留目标会话并重试",
    synthesisSave: "保存到这条结果",
    synthesisReplace: "替换综合结果",
    synthesisReplaceConfirm: "替换已保存的综合结果？",
    synthesisSaved: "综合结果",
    synthesisSavedDone: "综合结果已保存",
    synthesisCancel: "返回结果"
  },
  zhTW: {
    synthesisAction: "綜合所選答案",
    synthesisTitle: "輔助綜合",
    synthesisAnswers: "候選答案",
    synthesisCount: "已選 {count} 則答案",
    synthesisTarget: "目標 AI",
    synthesisTargetMissing: "請選擇目標 AI",
    synthesisTargetNotSelected: "請從目前已選網站中選擇目標 AI",
    synthesisTier: "模型檔位",
    synthesisInstruction: "綜合要求",
    synthesisDefaultInstruction: "比較這些答案，歸納共識與分歧，指出需要查證的內容，並給出綜合結論。不要把多數答案一致視為事實依據。",
    synthesisPreview: "內容預覽",
    synthesisTooLong: "內容超過 60,000 個字元，不會自動裁剪",
    synthesisNotEnough: "請至少選擇兩則答案",
    synthesisUnknownTier: "檔位未知",
    synthesisSend: "傳送以綜合",
    synthesisSending: "正在開啟目標網站的新對話…",
    synthesisSendFailed: "綜合要求傳送失敗",
    synthesisSent: "綜合要求已傳送；請觀察目標網站，完成後擷取結果",
    synthesisCollect: "擷取綜合結果",
    synthesisCollecting: "正在擷取目標網站的目前答案…",
    synthesisCollectFailed: "綜合結果擷取失敗，請保留目標對話並重試",
    synthesisSave: "儲存到這筆結果",
    synthesisReplace: "取代綜合結果",
    synthesisReplaceConfirm: "取代已儲存的綜合結果？",
    synthesisSaved: "綜合結果",
    synthesisSavedDone: "綜合結果已儲存",
    synthesisCancel: "返回結果"
  }
} as const;
