export const WORKSPACE_COPY = {
  en: {
    selectedSummary: "{selected} / {total} selected",
    sendingSummary: "Sending to {count} sites",
    failedSummary: "{count} selected sites failed",
    cancelledSummary: "Sending was cancelled for {count} selected sites",
    mixedFailureSummary: "Selected sites: {failed} failed, {cancelled} cancelled",
    retryFailedSites: "Retry {count} failed sites",
    retryCancelledSites: "Retry {count} cancelled sites",
    retryFailedOrCancelledSites: "Retry {count} failed or cancelled sites",
    newSessionDone: "New sessions opened for {count} selected sites",
    newSessionPartial: "New sessions opened for {ok} sites; {failed} failed",
    scope: "Site scope",
    closeScope: "Close site scope",
    newSessionSelected: "New session for selected sites",
    allSites: "All",
    clearSites: "Clear",
    imageSites: "Images",
    intlSites: "International",
    domesticSites: "Domestic",
    selectedSites: "Selected sites",
    savedGroups: "Saved groups",
    noSavedGroups: "No saved groups",
    groupNamePlaceholder: "Group name…",
    groupSelectionRequired: "Select at least 1 site to save a group",
    groupPresetReserved: "This scope is already available above",
    groupAlreadySaved: "This site combination is already saved",
    groupSaving: "Saving group…",
    saveGroup: "Save current selection",
    deleteGroup: "Delete {group}",
    confirmDeleteGroup: "Delete {group}?",
    confirmDelete: "Delete",
    cancelDelete: "Keep",
    workspaceActionFailed: "Workspace action failed",
    workbench: "Workbench",
    closeWorkbench: "Close workbench",
    selectSites: "Select sites",
    customScope: "Custom",
    sitesCompact: "Sites",
    chooseSavedGroup: "Choose a saved group",
    moreActions: "More actions",
    siteStatusSummary: "Page and adapter readiness",
    backToSiteStatus: "Back to site status",
    newSessionConfirmTitle: "Start new sessions?",
    newSessionConfirmMessage: "This will leave the current conversations on {count} selected sites and open a blank conversation on each.",
    newSessionConfirmAction: "Start new sessions",
    newSessionKeepCurrent: "Keep current conversations"
  },
  zhCN: {
    selectedSummary: "已选择 {selected} / {total}",
    sendingSummary: "正在向 {count} 个站点发送",
    failedSummary: "{count} 个已选站点失败",
    cancelledSummary: "{count} 个已选站点已取消发送",
    mixedFailureSummary: "已选站点：{failed} 个失败，{cancelled} 个已取消发送",
    retryFailedSites: "重试 {count} 个失败站点",
    retryCancelledSites: "重试 {count} 个已取消站点",
    retryFailedOrCancelledSites: "重试 {count} 个失败或已取消站点",
    newSessionDone: "已为 {count} 个已选站点新建会话",
    newSessionPartial: "已为 {ok} 个站点新建会话，{failed} 个失败",
    scope: "站点范围",
    closeScope: "关闭站点范围",
    newSessionSelected: "为已选站点新建会话",
    allSites: "全部",
    clearSites: "清空",
    imageSites: "支持图片",
    intlSites: "国外",
    domesticSites: "国内",
    selectedSites: "已选站点",
    savedGroups: "已存分组",
    noSavedGroups: "暂无分组",
    groupNamePlaceholder: "分组名称…",
    groupSelectionRequired: "至少选择 1 个站点后才能保存分组",
    groupPresetReserved: "这一范围已在上方提供",
    groupAlreadySaved: "这一站点组合已经保存",
    groupSaving: "正在保存分组…",
    saveGroup: "保存当前选择",
    deleteGroup: "删除{group}",
    confirmDeleteGroup: "删除{group}？",
    confirmDelete: "删除",
    cancelDelete: "保留",
    workspaceActionFailed: "工作区操作失败",
    workbench: "工作台",
    closeWorkbench: "关闭工作台",
    selectSites: "选择站点",
    customScope: "自定义",
    sitesCompact: "站点",
    chooseSavedGroup: "选择已存分组",
    moreActions: "更多操作",
    siteStatusSummary: "页面与适配器就绪情况",
    backToSiteStatus: "返回站点状态",
    newSessionConfirmTitle: "要新建会话吗？",
    newSessionConfirmMessage: "这会离开 {count} 个已选站点中的当前对话，并分别打开空白会话。",
    newSessionConfirmAction: "新建会话",
    newSessionKeepCurrent: "保留当前对话"
  },
  zhTW: {
    selectedSummary: "已選取 {selected} / {total}",
    sendingSummary: "正在傳送到 {count} 個網站",
    failedSummary: "{count} 個已選網站失敗",
    cancelledSummary: "{count} 個已選網站已取消傳送",
    mixedFailureSummary: "已選網站：{failed} 個失敗，{cancelled} 個已取消傳送",
    retryFailedSites: "重試 {count} 個失敗網站",
    retryCancelledSites: "重試 {count} 個已取消網站",
    retryFailedOrCancelledSites: "重試 {count} 個失敗或已取消網站",
    newSessionDone: "已為 {count} 個已選網站新增對話",
    newSessionPartial: "已為 {ok} 個網站新增對話，{failed} 個失敗",
    scope: "網站範圍",
    closeScope: "關閉網站範圍",
    newSessionSelected: "為已選網站新增對話",
    allSites: "全部",
    clearSites: "清除",
    imageSites: "支援圖片",
    intlSites: "國外",
    domesticSites: "國內",
    selectedSites: "已選網站",
    savedGroups: "已儲存群組",
    noSavedGroups: "尚無群組",
    groupNamePlaceholder: "群組名稱…",
    groupSelectionRequired: "至少選取 1 個網站後才能儲存群組",
    groupPresetReserved: "此範圍已在上方提供",
    groupAlreadySaved: "此網站組合已儲存",
    groupSaving: "正在儲存群組…",
    saveGroup: "儲存目前選取",
    deleteGroup: "刪除{group}",
    confirmDeleteGroup: "刪除{group}？",
    confirmDelete: "刪除",
    cancelDelete: "保留",
    workspaceActionFailed: "工作區操作失敗",
    workbench: "工作台",
    closeWorkbench: "關閉工作台",
    selectSites: "選擇網站",
    customScope: "自訂",
    sitesCompact: "網站",
    chooseSavedGroup: "選擇已儲存群組",
    moreActions: "更多操作",
    siteStatusSummary: "頁面與轉接器就緒狀況",
    backToSiteStatus: "返回網站狀態",
    newSessionConfirmTitle: "要新增對話嗎？",
    newSessionConfirmMessage: "這會離開 {count} 個已選網站中的目前對話，並分別開啟空白對話。",
    newSessionConfirmAction: "新增對話",
    newSessionKeepCurrent: "保留目前對話"
  }
} as const;
