export const WORKSPACE_COPY = {
  en: {
    selectedSummary: "{selected} / {total} selected",
    sendingSummary: "Sending to {count} sites",
    scope: "Site scope",
    closeScope: "Close site scope",
    newSessionSelected: "New session for selected sites",
    allSites: "All",
    clearSites: "Clear",
    imageSites: "Images",
    intlSites: "International",
    domesticSites: "Domestic",
    selectedSites: "Selected sites",
    savedGroups: "Saved groups",
    noSavedGroups: "No saved groups",
    groupNamePlaceholder: "Group name…",
    groupSelectionRequired: "Select at least 1 site to save a group",
    groupPresetReserved: "This scope is already available above",
    groupAlreadySaved: "This site combination is already saved",
    groupSaving: "Saving group…",
    saveGroup: "Save current selection",
    deleteGroup: "Delete {group}",
    confirmDeleteGroup: "Delete {group}?",
    confirmDelete: "Delete",
    cancelDelete: "Keep",
    workspaceActionFailed: "Workspace action failed"
  },
  zhCN: {
    selectedSummary: "已选择 {selected} / {total}",
    sendingSummary: "正在向 {count} 个站点发送",
    scope: "站点范围",
    closeScope: "关闭站点范围",
    newSessionSelected: "为已选站点新建会话",
    allSites: "全部",
    clearSites: "清空",
    imageSites: "支持图片",
    intlSites: "国外",
    domesticSites: "国内",
    selectedSites: "已选站点",
    savedGroups: "已存分组",
    noSavedGroups: "暂无分组",
    groupNamePlaceholder: "分组名称…",
    groupSelectionRequired: "至少选择 1 个站点后才能保存分组",
    groupPresetReserved: "这一范围已在上方提供",
    groupAlreadySaved: "这一站点组合已经保存",
    groupSaving: "正在保存分组…",
    saveGroup: "保存当前选择",
    deleteGroup: "删除{group}",
    confirmDeleteGroup: "删除{group}？",
    confirmDelete: "删除",
    cancelDelete: "保留",
    workspaceActionFailed: "工作区操作失败"
  },
  zhTW: {
    selectedSummary: "已選取 {selected} / {total}",
    sendingSummary: "正在傳送到 {count} 個網站",
    scope: "網站範圍",
    closeScope: "關閉網站範圍",
    newSessionSelected: "為已選網站新增對話",
    allSites: "全部",
    clearSites: "清除",
    imageSites: "支援圖片",
    intlSites: "國外",
    domesticSites: "國內",
    selectedSites: "已選網站",
    savedGroups: "已儲存群組",
    noSavedGroups: "尚無群組",
    groupNamePlaceholder: "群組名稱…",
    groupSelectionRequired: "至少選取 1 個網站後才能儲存群組",
    groupPresetReserved: "此範圍已在上方提供",
    groupAlreadySaved: "此網站組合已儲存",
    groupSaving: "正在儲存群組…",
    saveGroup: "儲存目前選取",
    deleteGroup: "刪除{group}",
    confirmDeleteGroup: "刪除{group}？",
    confirmDelete: "刪除",
    cancelDelete: "保留",
    workspaceActionFailed: "工作區操作失敗"
  }
} as const;
